SELECT
    B.YEAR AS YEAR,
    B.MAX_SIZE - A.SIZE_OF_COLONY AS YEAR_DEV,
    A.ID
FROM
    ECOLI_DATA A
    INNER JOIN (
    SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM
    ECOLI_DATA
    GROUP BY
    YEAR(DIFFERENTIATION_DATE)
    ) B
ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY
    B.YEAR ASC,
    YEAR_DEV ASC;

-- 아래는 윈도우 함수 적용

SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) OVER(PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA
ORDER BY 1, 2;