SELECT INFO.FLAVOR
FROM FIRST_HALF HALF INNER JOIN ICECREAM_INFO INFO
ON HALF.FLAVOR = INFO.FLAVOR
WHERE HALF.TOTAL_ORDER > 3000 AND INFO.INGREDIENT_TYPE = 'fruit_based'
ORDER BY HALF.TOTAL_ORDER DESC;