SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
INNER JOIN ITEM_TREE B ON A.ITEM_ID = B.ITEM_ID
INNER JOIN ITEM_INFO C ON B.PARENT_ITEM_ID = C.ITEM_ID
WHERE C.RARITY = 'RARE'
ORDER BY A.ITEM_ID DESC