# 풀이
SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID,
       R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD B JOIN USED_GOODS_REPLY R
                             ON B.BOARD_ID = R.BOARD_ID
WHERE YEAR(R.CREATED_DATE) = 2022 AND MONTH(R.CREATED_DATE) = 10
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;

# 다른 사람 풀이 -> SUBSTR 함수 적용
SELECT  A.TITLE, A.BOARD_ID, B.REPLY_ID,
        B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CRAETED_DATE
FROM  USED_GOODS_BOARD AS A INNER JOIN  USED_GOODS_REPLY AS B
ON  A.BOARD_ID = B.BOARD_ID
WHERE  SUBSTR(A.CREATED_DATE,1,7) = '2022-10'
ORDER BY  B.CREATED_DATE ASC, A.TITLE ASC;