SELECT ID
FROM ECOLI_DATA
WHERE PARENTID IN (
-- PARENTID가 1세대인 2세대 대장균을 찾는다.
    SELECT ID
    FROM ECOLI_DATA
    WHERE PARENTID IN (
-- PARENTID가 NULL인 1세대 대장균을 찾는다.
        SELECT ID
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NULL))
ORDER BY ID

-- 또는

SELECT D3.ID
FROM ECOLI_DATA D1
INNER JOIN ECOLI_DATA D2
ON D1.ID = D2.PARENT_ID -- D2의 부모가 D1임을 의미 즉, D2는 D1의 자식 2세대
INNER JOIN ECOLI_DATA D3
ON D2.ID = D3.PARENT_ID -- D3의 부모가 D2임을 의미 즉, D3는 D2의 자식 3세대
WHERE D1.PARENT_ID IS NULL -- 1세대부터 시작하는 대장균을 선택
ORDER BY D3.ID