-- 재귀 CTE 풀이
WITH RECURSIVE WON AS (
    SELECT 0 AS PRICE_GROUP
    UNION ALL
    SELECT PRICE_GROUP + 10000
    FROM WON
    WHERE PRICE_GROUP < (SELECT MAX(PRICE) FROM PRODUCT)
)

SELECT PRICE_GROUP, COUNT(P.PRICE) AS PRODUCTS
FROM WON AS W
JOIN PRODUCT AS P ON W.PRICE_GROUP <= P.PRICE AND P.PRICE < (W.PRICE_GROUP + 10000)
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP

-- TRUNCATE 함수 풀이
SELECT TRUNCATE(PRICE/10000,0) * 10000 AS PRICE_GROUP, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY TRUNCATE(PRICE/10000,0) * 10000
ORDER BY PRICE_GROUP