SELECT NAME, COUNT
FROM ( SELECT NAME, COUNT(NAME) AS COUNT FROM ANIMAL_INS GROUP BY NAME) AS COUNT_ANIAML
WHERE COUNT >= 2
ORDER BY NAME ASC

--

SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) >= 2
ORDER BY NAME