SELECT EMP_NO, EMP_NAME, GRADE,
      CASE
          WHEN GRADE = 'S' THEN SAL*0.2
          WHEN GRADE = 'A' THEN SAL*0.15
          WHEN GRADE = 'B' THEN SAL*0.1
          ELSE 0 END AS BONUS

FROM (SELECT HRE.EMP_NO, HRE.EMP_NAME,
      CASE
          WHEN AVG(HRG.SCORE) >= 96 THEN 'S'
          WHEN AVG(HRG.SCORE) >= 90 THEN 'A'
          WHEN AVG(HRG.SCORE) >= 80 THEN 'B'
          ELSE 'C' END AS GRADE,
      HRE.SAL
      FROM HR_EMPLOYEES AS HRE JOIN HR_GRADE AS HRG
      USING (EMP_NO)
      GROUP BY HRE.EMP_NO, HRE.EMP_NAME, HRE.SAL) AS INFO
ORDER BY EMP_NO ASC
