SELECT HG.SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM (SELECT EMP_NO, SUM(SCORE) AS SCORE FROM HR_GRADE WHERE YEAR = 2022 GROUP BY EMP_NO) AS HG
JOIN HR_EMPLOYEES AS HE USING(EMP_NO)
ORDER BY SCORE DESC
LIMIT 1