SELECT COUNT(*) AS FISH_COUNT, MAX(FI.LENGTH) AS MAX_LENGTH, FI.FISH_TYPE
FROM (SELECT FISH_TYPE, AVG(IFNULL(LENGTH, 10)) AS AVG_LENGTH
      FROM FISH_INFO
      GROUP BY FISH_TYPE) FISH_AVG
JOIN FISH_INFO FI USING(FISH_TYPE)
WHERE AVG_LENGTH >= 33
GROUP BY FI.FISH_TYPE
ORDER BY FI.FISH_TYPE ASC