SELECT CAR_ID, ROUND(RENT_DAY, 1) AS AVERAGE_DURATION
FROM (SELECT CAR_ID, AVG(DATEDIFF(END_DATE, START_DATE) + 1) AS RENT_DAY FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY GROUP BY CAR_ID) AS SUB
WHERE RENT_DAY >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

-- HAVING절 사용
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
HAVING ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC