WITH TBL AS (
    SELECT SUM(CODE) AS SUM_CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D INNER JOIN TBL T ON D.SKILL_CODE & T.SUM_CODE > 0
ORDER BY D.ID ASC;