-- 1. 회원별 리뷰 수 생성
WITH CTE1 AS (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
), -- 2. CTE1에서 회원 별 최대 리뷰 수 CTE2 생성
    CTE2 AS (
        SELECT MAX(REVIEW_COUNT) AS MAX_COUNT
        FROM CTE1
)

SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM CTE1 INNER JOIN CTE2 ON CTE1.REVIEW_COUNT = CTE2.MAX_COUNT
INNER JOIN REST_REVIEW RR USING(MEMBER_ID)
INNER JOIN MEMBER_PROFILE MP USING(MEMBER_PROFILE)
ORDER BY REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;