WITH TOTAL_AMOUNT AS (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_AMOUNT
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
)

SELECT P.PRODUCT_CODE, TA.TOTAL_AMOUNT * P.PRICE AS SALES
FROM PRODUCT P JOIN TOTAL_AMOUNT TA USING(PRODUCT_ID)
ORDER BY SALES DESC, PRODUCT_CODE ASC

---

SELECT P.PRODUCT_CODE, SUM(P.PRICE * O.SALES_AMOUNT) AS SALES
FROM PORDUCT P JOIN OFFLINE_SALE O USING(PRODUCT_ID)
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE ASC