WITH TBL AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT
    YEAR(OS.SALES_DATE) AS YEAR,
    MONTH(OS.SALES_DATE) AS MONTH,
    COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT OS.USER_ID) / (SELECT COUNT(*) FROM TBL), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE OS JOIN TBL T USING(USER_ID)
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;