SELECT INS.ANIMAL_ID, INS.ANIMAL_NAME
FROM ANIMAL_INS INS JOIN ANIMNAL_OUTS OUTS USING(ANIMAL_ID)
WHERE INS.DATETIME > OUTS.DATETIME -- 보호 시작일보다 입양일이 더 빠른 경우
ORDER BY INS.DATETIME ASC

---

-- TIMEDIFF 활용
SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS INS JOIN ANIMAL_OUTS OUTS USING(ANIMAL_ID)
WHERE TIMEDIFF(INS.DATETIME, OUTS.DATETIME) > 0
ORDER BY INS.DATETIME ASC;