WITH SUM_FLAVOR AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS FLAVOR_SUM
    FROM JULY
    GROUP BY FLAVOR
)

SELECT FLAVOR
FROM FIRST_HALF FH JOIN SUM_FLAVOR SF USING(FLAVOR)
ORDER BY FH.TOTAL_ORDER + SF.FLAVOR_SUM DESC
LIMIT 3;