WITH POSSIBLE_CAR AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN ('세단', 'SUV') AND
          CAR_ID NOT IN (SELECT CAR_ID -- 11월에 대여 기록이 있는 차들 SELECT
                         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                         WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
)

SELECT PC.CAR_ID, PC.CAR_TYPE, FLOOR(PC.DAILY_FEE * (100-CRCDP.DISCOUNT_RATE) * 0.01 * 30) AS FEE
FROM POSSIBLE_CAR PC JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
USING(CAR_TYPE)
WHERE DURATION_TYPE = '30일 이상' AND
    FLOOR(PC.DAILY_FEE * (100-CRCDP.DISCOUNT_RATE) * 0.01 * 30) >= 500000 AND
    FLOOR(PC.DAILY_FEE * (100-CRCDP.DISCOUNT_RATE) * 0.01 * 30) < 2000000
ORDER BY FEE DESC, PC.CAR_TYPE ASC, PC.CAR_ID DESC