# 중고 거래 게시판 정보 : USED_GOODS_BOARD
# 중고 거래 게시판 사용자 정보 : USED_GOODS_USER

SELECT UGU.USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UGB JOIN USED_GOODS_USER UGU
ON UGB.WRITER_ID = UGU.USER_ID
WHERE UGB.STATUS = 'DONE'
GROUP BY UGU.USER_ID, UGU.NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC