-- PRODUCT : 의류 쇼핑몰에서 판매중인 상품들의 정보
/**
PRODUCT_ID : 상품 ID
PRODUCT_CODE : 상품 코드
PRICE : 판매가
*/

SELECT TRUNCATE(PRICE / 10000, 0) * 10000 AS PRICE_GROUP, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY TRUNCATE(PRICE / 10000, 0) * 10000
ORDER BY PRICE_GROUP ASC