-- USER_INFO : 의류 쇼핑몰에 가입한 회원 정보
    -- 성별 : 0인 경우 남자, 1인 경우 여자
-- ONLINE_SALE : 온라인 상품 판매 정보

-- 한 회원이 2022년 1월 달 내에 여러 개의 상품을 구매할 수 있으니 COUNT(DISTINCT USER_ID) 처리
SELECT YEAR(OS.SALES_DATE) AS YEAR, MONTH(OS.SALES_DATE) AS MONTH, UI.GENDER, COUNT(DISTINCT OS.USER_ID) AS USERS
FROM USER_INFO UI INNER JOIN ONLINE_SALE OS USING(USER_ID)
WHERE UI.GENDER IS NOT NULL
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), UI.GENDER
ORDER BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE), UI.GENDER