-- HR_DEPARTMENT : 회사의 부서 정보를 담은 테이블
-- HR_EMPLOYEES : 회사의 사원 정보를 담은 테이블

SELECT HRD.DEPT_ID, HRD.DEPT_NAME_EN, ROUND(AVG(SAL), 0) AS AVG_SAL
FROM HR_DEPARTMENT HRD INNER JOIN HR_EMPLOYEES HRE USING(DEPT_ID)
GROUP BY HRD.DEPT_ID, HRD.DEPT_NAME_KR
ORDER BY AVG_SAL DESC