-- HR_DEPARTMENT : 회사의 부서 정보를 담은 테이블
-- HR_EMPLOYEES : 회사의 사원 정보를 담은 테이블
-- HR_GRADE : 2022년 사원의 평가 정보를 담은 테이블

SELECT TS.SCORE, HRE.EMP_NO, HRE.EMP_NAME, HRE.POSITION, HRE.EMAIL
FROM (SELECT EMP_NO, SUM(SCORE) AS SCORE FROM HR_GRADE WHERE YEAR = 2022 GROUP BY EMP_NO) AS TS
INNER JOIN HR_EMPLOYEES HRE USING(EMP_NO)
ORDER BY TS.SCORE DESC
LIMIT 1